include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    avoid_print: false
    prefer_single_quotes: false
    unawaited_futures: true
    package_api_docs: true
    # Require absolute package imports
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    no_adjacent_strings_in_list: true
    always_declare_return_types: true
    avoid_catching_errors: true
    use_to_and_as_if_applicable: true