name: yomikun
description: Yomikun teaches you how to read Japanese names.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2
  path_provider: any
  path: ^1.8.0
  easy_dynamic_theme: ^2.2.0
  collection: ^1.15.0

  # Stream extension methods
  rxdart: ^0.27.3

  # Visualisation
  fl_chart: ^0.41.0
  treemap: ^0.4.0

  # For romaji <-> kana conversion
  kana_kit: ^2.0.0

  # For unicode denormalisation
  unorm_dart: ^0.2.0

  # For local persistent state
  hive_flutter: ^1.1.0
  hive: ^2.0.5

  # For sharing
  share_plus: ^3.0.4

  # For state management
  hooks_riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  riverpod:
    git:
      url: https://github.com/rrousselGit/river_pod.git
      path: packages/riverpod
      ref: master
  equatable: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_slidable: ^1.1.0

dependency_overrides:
  riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  sqflite_common_ffi: ^2.1.0+1

  flutter_lints: ^1.0.0

  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
   - assets/names.db

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "appicon.png"