name: yomikun
description: Yomikun teaches you how to read Japanese names.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+3

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  camera: ^0.11.2
  collection: ^1.19.1
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.1
  freezed_annotation: null
  google_mlkit_text_recognition: ^0.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  image_picker: ^1.2.0
  intl: any
  kana_kit: ^2.1.1
  path: ^1.8.2
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  rxdart: ^0.28.0
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  sqflite:
  sqflite_common_ffi: any
  synchronized: ^3.4.0
  treemap: ^0.4.0
  unorm_dart: ^0.3.1+1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  json_annotation: ^4.0.1

# Project uses Hive which has not been updated for many years.
# This prevents newer packages from installing due to dep conflicts
# so override Hive's deps.
dependency_overrides:
  source_gen: ^3.1.0
  source_helper: ^1.3.7
  analyzer: ^8.1.1
  build_runner: ^2.8.0
  build: ^3.0.2

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  hive_generator: ^2.0.1
  json_serializable: ^6.5.4
  flutter_gen: ^5.12.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/namesdb.sqlite3
    - assets/namesdb.version.txt
    - assets/sidemenu_splash.jpg
    - assets/appicon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "appicon.png"
