name: yomikun
description: Yomikun teaches you how to read Japanese names.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  sqflite: ^2.0.2
  path_provider: any
  path: ^1.8.0
  synchronized: ^3.0.0
  rxdart: ^0.27.3
  collection: ^1.15.0
  freezed_annotation:

  # Visualisation
  fl_chart: ^0.41.0
  treemap: ^0.4.0

  # For romaji <-> kana conversion
  kana_kit: ^2.0.0

  # For unicode denormalisation
  unorm_dart: ^0.2.0

  # For local persistent state
  hive_flutter: ^1.1.0
  hive: ^2.0.5
  shared_preferences: ^2.0.12

  # For sharing
  share_plus: ^3.0.4

  # For state management
  riverpod: ^2.0.0-dev.0
  hooks_riverpod: ^2.0.0-dev.0
  flutter_riverpod: ^2.0.0-dev.0
  flutter_hooks: ^0.18.2+1
  equatable: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_slidable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
 
  sqflite_common_ffi: ^2.1.0+1
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2 
  hive_generator: ^1.1.2
  freezed:

flutter:
  generate: true
  uses-material-design: true

  assets:
   - assets/names.db
   - assets/sidemenu_splash.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "appicon.png"