name: yomikun
description: Yomikun teaches you how to read Japanese names.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+3

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  camera: ^0.10.1
  collection: ^1.15.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_slidable: ^2.0.0
  freezed_annotation: null
  google_mlkit_text_recognition: ^0.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  kana_kit: ^2.0.0
  path: ^1.8.2
  path_provider: any
  riverpod: ^2.1.1
  rxdart: ^0.27.3
  share_plus: ^6.3.0
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  synchronized: ^3.0.0
  treemap: ^0.4.0
  unorm_dart: ^0.2.0
  url_launcher: ^6.0.18
  package_info_plus: ^3.0.2
  json_annotation: ^4.0.1
  sqflite_common_ffi: ^2.2.0+1

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: null
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/namesdb.sqlite3
    - assets/namesdb.version.txt
    - assets/sidemenu_splash.jpg
    - assets/appicon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "appicon.png"
